[package]
name = "wasm-locality-attribute"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
proxy-wasm = "0.2.1"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
